# Generated by Django 3.0.5 on 2020-05-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Category',), 'verbose_name_plural': ('Categories',)},
        ),
    ]
