# Generated by Django 3.0.5 on 2020-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200511_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Cover image'),
        ),
    ]
